# Generated by Django 6.0 on 2026-08-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='personal_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Disappoint'), (3, '3 - Average'), (4, '4 - Enjoyable'), (5, '5 - Masterpiece')], null=True),
        ),
    ]
